# Generated by Django 5.1 on 2024-10-13 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('Apple', 'Apple'), ('Pear', 'Pear'), ('Hourglass', 'Hourglass'), ('Rectangle', 'Rectangle'), ('Curvy', 'Curvy'), ('Plus Size', 'Plus Size')], max_length=20)),
                ('skin_tone', models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Olive', 'Olive'), ('Dark', 'Dark')], max_length=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('Teens', 'Teens (13-19)'), ('20s', '20s'), ('30s', '30s'), ('40s', '40s and above')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
